version: '3.8'

services:
  tomcat:
    image: tomcat:10.1.15-jdk17
    container_name: tomcat
    ports:
      - 8000:8080
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    environment:
      - TZ=Asia/Tokyo
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MEMORY_LIMIT: 128M
      UPLOAD_LIMIT: 64M
    restart: always
    ports:
      - "8080:80"
volumes:
    db_data: {}
