version: '3.8'

services:
  tomcat:
    image: tomcat:9.0.70-jdk17
    container_name: tomcat
    ports:
      - 8080:8080
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    environment:
      - TZ=Asia/Tokyo
    restart: always